export interface SignText {
  title: string
  keywords: string[]
  style: string // adverbial phrase: "de forma ..."
  essence: string
  light: string
  shadow: string
  sun: string
  moon: string
  asc: string
  myth: string
}

export const SIGN_TEXT: SignText[] = [
  {
    title: 'O Pioneiro',
    keywords: ['coragem', 'iniciativa', 'impulso', 'liderança', 'autenticidade'],
    style: 'de forma direta, corajosa e impulsiva',
    essence: 'Áries é a primeira centelha do zodíaco — o instante em que a vida rompe a semente. É fogo cardinal: pura vontade de começar, de existir e de se afirmar.',
    light: 'Coragem para abrir caminhos, franqueza, energia contagiante e capacidade de agir quando todos hesitam.',
    shadow: 'Impaciência, impulsividade, dificuldade em terminar o que começa e reações explosivas.',
    sun: 'Seu Sol em Áries revela uma alma de pioneira: você se sente vivo quando enfrenta desafios e inaugura algo novo. Sua identidade se fortalece pela ação — esperar não é natural para você. O aprendizado da vida é canalizar essa chama sem queimar pontes, descobrindo que a verdadeira coragem também sabe ouvir.',
    moon: 'Com a Lua em Áries, suas emoções surgem rápidas e intensas como faíscas — e passam com a mesma velocidade. Você precisa de liberdade e de movimento para se sentir seguro, e nutre-se de desafios. Aprender a sentir antes de reagir traz paz ao seu coração guerreiro.',
    asc: 'Ascendente em Áries: você chega ao mundo com presença marcante, energia e franqueza. As pessoas percebem em você alguém decidido e direto. A vida pede que você tome a frente — e que aprenda a dosar a pressa.',
    myth: 'O Carneiro do Velocino de Ouro, que resgatou Frixo e Hele, simboliza a coragem que salva e inaugura jornadas heroicas.',
  },
  {
    title: 'O Construtor',
    keywords: ['estabilidade', 'sensualidade', 'paciência', 'valor', 'natureza'],
    style: 'de forma estável, sensorial e perseverante',
    essence: 'Touro é a terra fértil da primavera, o florescer que se enraíza. Fixo e venusiano, busca segurança, beleza e prazer nas coisas concretas e duradouras.',
    light: 'Constância, lealdade, senso estético, capacidade de construir com paciência e presença calma.',
    shadow: 'Teimosia, apego excessivo, resistência a mudanças e acomodação.',
    sun: 'Seu Sol em Touro mostra uma essência que floresce no tempo certo. Você constrói sua identidade sobre valores sólidos, aprecia a beleza e o conforto e possui uma força serena que sustenta a todos ao redor. O caminho é descobrir que a verdadeira segurança nasce de dentro.',
    moon: 'Com a Lua em Touro — sua exaltação — as emoções buscam calma, rotina e prazeres simples. Comida boa, toque, natureza e estabilidade alimentam sua alma. Você oferece um porto seguro aos outros e precisa aprender a soltar o que já não floresce.',
    asc: 'Ascendente em Touro: sua presença transmite tranquilidade, firmeza e charme natural. Você aborda a vida com cautela e prefere o caminho seguro. Sua beleza está na constância.',
    myth: 'O Touro branco de Zeus, que conduziu Europa através do mar, representa a força gentil e a fertilidade divina.',
  },
  {
    title: 'O Mensageiro',
    keywords: ['curiosidade', 'comunicação', 'versatilidade', 'ideias', 'conexão'],
    style: 'de forma curiosa, comunicativa e versátil',
    essence: 'Gêmeos é o ar mutável que circula, conecta e troca. Regido por Mercúrio, é a mente que pergunta, aprende e cria pontes entre mundos.',
    light: 'Inteligência ágil, humor, adaptabilidade, talento para aprender e ensinar.',
    shadow: 'Dispersão, inquietude, superficialidade e dificuldade em se comprometer.',
    sun: 'Seu Sol em Gêmeos revela uma essência brilhante e inquieta: você se realiza trocando ideias, aprendendo e conectando pessoas. Sua identidade é múltipla — e isso é um dom. O desafio é unir as muitas vozes internas num propósito que dê profundidade à sua leveza.',
    moon: 'Com a Lua em Gêmeos, você processa sentimentos conversando, escrevendo e entendendo. Precisa de estímulo mental para se sentir bem e pode racionalizar as emoções. Conectar-se com o corpo e o silêncio ajuda seu coração a se aquietar.',
    asc: 'Ascendente em Gêmeos: você chega ao mundo com jovialidade, curiosidade e conversa fácil. As pessoas o percebem como alguém leve, rápido e espirituoso. A vida é, para você, uma grande sala de aula.',
    myth: 'Castor e Pólux, os gêmeos — um mortal e outro imortal — que dividiram a eternidade por amor fraterno.',
  },
  {
    title: 'O Guardião',
    keywords: ['acolhimento', 'memória', 'família', 'sensibilidade', 'proteção'],
    style: 'de forma sensível, protetora e emocional',
    essence: 'Câncer é a água cardinal, o útero do zodíaco. Regido pela Lua, guarda memórias, nutre e protege tudo aquilo que ama.',
    light: 'Empatia profunda, cuidado, intuição, lealdade e capacidade de criar lar onde estiver.',
    shadow: 'Melindre, apego ao passado, mudanças de humor e defesa excessiva.',
    sun: 'Seu Sol em Câncer revela uma essência que brilha ao cuidar. Você sente o mundo com o coração e constrói sua identidade a partir dos laços afetivos e das raízes. Sua força é a sensibilidade — o aprendizado é proteger-se sem se fechar em sua concha.',
    moon: 'Com a Lua em Câncer — seu domicílio — suas emoções são profundas, intuitivas e cheias de memória. Você precisa de um ninho seguro e de vínculos verdadeiros. Sua capacidade de acolher é imensa; lembre-se de acolher também a si mesmo.',
    asc: 'Ascendente em Câncer: você se apresenta com doçura, reserva e sensibilidade. As pessoas sentem em você acolhimento. Você testa o ambiente antes de se abrir — e, quando se abre, é para sempre.',
    myth: 'O Caranguejo enviado por Hera contra Hércules, eternizado nas estrelas por sua lealdade.',
  },
  {
    title: 'O Rei Solar',
    keywords: ['criatividade', 'brilho', 'generosidade', 'coração', 'expressão'],
    style: 'de forma criativa, calorosa e expressiva',
    essence: 'Leão é o fogo fixo do auge do verão, o Sol no seu trono. É o coração que irradia, cria e celebra a vida com nobreza.',
    light: 'Generosidade, carisma, criatividade, lealdade e capacidade de inspirar.',
    shadow: 'Orgulho, necessidade de aplauso, dramatização e dificuldade de reconhecer erros.',
    sun: 'Seu Sol em Leão — em domicílio — revela uma essência nascida para brilhar. Você precisa expressar sua criatividade e ser reconhecido pelo seu coração generoso. Seu caminho é descobrir que a luz mais intensa é aquela que ilumina os outros sem precisar de plateia.',
    moon: 'Com a Lua em Leão, você precisa sentir-se amado, admirado e especial. Suas emoções são calorosas, dramáticas e leais. Brincar, criar e celebrar nutrem sua alma — e o reconhecimento mais importante é o seu próprio.',
    asc: 'Ascendente em Leão: sua presença é magnética, solar e marcante. Você entra num lugar e ele se ilumina. A vida pede que você assuma seu palco com autenticidade.',
    myth: 'O Leão de Nemeia, de pele invulnerável, vencido por Hércules — símbolo da força que precisa ser nobre.',
  },
  {
    title: 'O Artesão',
    keywords: ['análise', 'serviço', 'saúde', 'aperfeiçoamento', 'discernimento'],
    style: 'de forma analítica, cuidadosa e prática',
    essence: 'Virgem é a terra mutável da colheita: separa o trigo do joio. Regido por Mercúrio, busca a perfeição através do serviço, do método e do cuidado.',
    light: 'Discernimento, utilidade, dedicação, atenção aos detalhes e sabedoria do corpo.',
    shadow: 'Autocrítica, perfeccionismo, ansiedade e preocupação excessiva.',
    sun: 'Seu Sol em Virgem revela uma essência que brilha pelo aperfeiçoamento. Você encontra sentido em ser útil, em organizar o caos e em cuidar dos detalhes que os outros não veem. O aprendizado é aceitar a imperfeição como parte sagrada da vida.',
    moon: 'Com a Lua em Virgem, você se sente seguro quando a vida está em ordem. Demonstra amor através de atos de cuidado práticos. Sua mente analítica pode gerar preocupação; rituais simples e o contato com a natureza acalmam seu coração.',
    asc: 'Ascendente em Virgem: você se apresenta discreto, observador e elegante na simplicidade. As pessoas percebem em você competência e confiabilidade. A vida o convida a servir sem se esquecer.',
    myth: 'Astreia, a virgem das estrelas, deusa da justiça que segura a espiga de trigo — a colheita da sabedoria.',
  },
  {
    title: 'O Diplomata',
    keywords: ['harmonia', 'parceria', 'beleza', 'justiça', 'equilíbrio'],
    style: 'de forma harmoniosa, elegante e cooperativa',
    essence: 'Libra é o ar cardinal do equinócio, quando dia e noite se equilibram. Regido por Vênus, busca o belo, o justo e o encontro com o outro.',
    light: 'Diplomacia, senso estético, empatia relacional, justiça e capacidade de mediar.',
    shadow: 'Indecisão, dependência da aprovação, evitação de conflitos.',
    sun: 'Seu Sol em Libra revela uma essência que se reconhece no encontro. Você busca harmonia, beleza e justiça, e floresce nas parcerias. O caminho é encontrar o equilíbrio dentro de si, sem abrir mão da própria voz para agradar.',
    moon: 'Com a Lua em Libra, você precisa de paz, beleza e companhia para se sentir bem. Conflitos o desestabilizam. Aprender que o desacordo também pode ser amoroso liberta seu coração.',
    asc: 'Ascendente em Libra: você se apresenta com charme, gentileza e elegância. As pessoas o percebem como agradável e conciliador. A vida o convida a relacionar-se — e a escolher.',
    myth: 'A Balança de Têmis e Astreia, que pesa as almas e mede a justiça entre deuses e humanos.',
  },
  {
    title: 'O Alquimista',
    keywords: ['intensidade', 'transformação', 'mistério', 'profundidade', 'poder'],
    style: 'de forma intensa, profunda e transformadora',
    essence: 'Escorpião é a água fixa do outono, quando as folhas caem e a vida se recolhe para renascer. Regido por Plutão e Marte, conhece os segredos da morte e do renascimento.',
    light: 'Profundidade, lealdade, coragem emocional, poder de regeneração e percepção aguçada.',
    shadow: 'Ciúme, controle, desconfiança e tendência a guardar mágoas.',
    sun: 'Seu Sol em Escorpião revela uma essência magnética e profunda. Você não aceita superficialidades: busca a verdade por trás das máscaras. Sua vida é feita de mortes e renascimentos — e a cada um deles você se torna mais poderoso.',
    moon: 'Com a Lua em Escorpião, você sente tudo intensamente, ainda que em silêncio. Confiança é sagrada para você. A cura vem quando você permite que as emoções fluam e se transformem, em vez de guardá-las.',
    asc: 'Ascendente em Escorpião: sua presença é intensa, misteriosa e penetrante. As pessoas sentem que você enxerga além. A vida o convida à transformação constante.',
    myth: 'O Escorpião que venceu o gigante Órion, e a Fênix que renasce das próprias cinzas.',
  },
  {
    title: 'O Buscador',
    keywords: ['expansão', 'sabedoria', 'liberdade', 'fé', 'aventura'],
    style: 'de forma expansiva, otimista e aventureira',
    essence: 'Sagitário é o fogo mutável, a flecha lançada ao horizonte. Regido por Júpiter, busca sentido, verdade, viagem e sabedoria.',
    light: 'Otimismo, generosidade, visão ampla, senso de humor e fé na vida.',
    shadow: 'Exagero, impaciência com limites, dogmatismo e promessas excessivas.',
    sun: 'Seu Sol em Sagitário revela uma essência de explorador. Você brilha quando aprende, ensina, viaja ou encontra um sentido maior. Sua fé ilumina os outros — e o aprendizado é transformar o entusiasmo em sabedoria encarnada.',
    moon: 'Com a Lua em Sagitário, você precisa de liberdade e horizonte para se sentir em paz. Emoções pesadas são enfrentadas com humor e filosofia. Permitir-se também sentir a tristeza aprofunda sua alegria.',
    asc: 'Ascendente em Sagitário: você chega com entusiasmo, franqueza e alegria. As pessoas percebem um espírito livre. A vida é, para você, uma aventura de descobertas.',
    myth: 'Quíron, o centauro sábio e curador ferido, mestre de heróis, que mira suas flechas nas estrelas.',
  },
  {
    title: 'O Mestre',
    keywords: ['ambição', 'disciplina', 'responsabilidade', 'estrutura', 'tempo'],
    style: 'de forma responsável, estratégica e disciplinada',
    essence: 'Capricórnio é a terra cardinal do solstício de inverno, a montanha a ser escalada. Regido por Saturno, ensina que tudo o que é grande se constrói com tempo.',
    light: 'Maturidade, perseverança, competência, integridade e senso de propósito.',
    shadow: 'Rigidez, pessimismo, excesso de controle e dificuldade em relaxar.',
    sun: 'Seu Sol em Capricórnio revela uma essência que cresce com o tempo, como os bons vinhos. Você busca realizar algo sólido e significativo. Sua determinação é admirável — e o aprendizado é permitir-se leveza e afeto pelo caminho até o topo.',
    moon: 'Com a Lua em Capricórnio, você aprendeu cedo a ser responsável pelas próprias emoções. Sente segurança quando tem controle e estrutura. Permitir-se ser cuidado é sua grande cura.',
    asc: 'Ascendente em Capricórnio: você se apresenta sério, confiável e reservado. As pessoas percebem maturidade. Com o tempo, você rejuvenesce e revela um humor sutil.',
    myth: 'Amalteia, a cabra que amamentou Zeus, e Pã, que se transformou em cabra-peixe para escapar de Tifão.',
  },
  {
    title: 'O Visionário',
    keywords: ['originalidade', 'liberdade', 'futuro', 'coletivo', 'inovação'],
    style: 'de forma original, livre e inovadora',
    essence: 'Aquário é o ar fixo, o portador das águas que despeja conhecimento sobre a humanidade. Regido por Urano e Saturno, une a visão do futuro ao compromisso com o coletivo.',
    light: 'Originalidade, ideais humanitários, amizade, mente inventiva e autenticidade.',
    shadow: 'Distanciamento emocional, rebeldia sem causa, teimosia intelectual.',
    sun: 'Seu Sol em Aquário revela uma essência à frente do seu tempo. Você brilha sendo autêntico e contribuindo para algo maior que você. Seu caminho é unir a mente visionária ao calor do coração.',
    moon: 'Com a Lua em Aquário, você precisa de espaço e liberdade para sentir. Observa suas emoções com certo distanciamento. Amizades verdadeiras e causas coletivas nutrem sua alma.',
    asc: 'Ascendente em Aquário: você se apresenta com originalidade, simpatia e um toque de excentricidade. As pessoas o percebem como único. A vida o convida a ser você mesmo, sem concessões.',
    myth: 'Ganimedes, o jovem levado ao Olimpo para servir a ambrosia — a sabedoria derramada sobre a humanidade.',
  },
  {
    title: 'O Místico',
    keywords: ['compaixão', 'intuição', 'imaginação', 'transcendência', 'fusão'],
    style: 'de forma intuitiva, compassiva e imaginativa',
    essence: 'Peixes é a água mutável, o oceano onde todos os rios se encontram. Regido por Netuno e Júpiter, dissolve fronteiras e conecta com o divino.',
    light: 'Compaixão, sensibilidade artística, intuição, espiritualidade e amor incondicional.',
    shadow: 'Escapismo, confusão, vitimismo e dificuldade com limites.',
    sun: 'Seu Sol em Peixes revela uma essência sensível e mística. Você sente o que não é dito e tem acesso a camadas sutis da realidade. Seu dom é a compaixão e a imaginação — o aprendizado é ter limites para que seu oceano não o afogue.',
    moon: 'Com a Lua em Peixes, você absorve as emoções do ambiente como uma esponja. Precisa de momentos de recolhimento, música, arte e espiritualidade. Sua intuição é um oráculo — confie nela.',
    asc: 'Ascendente em Peixes: você se apresenta suave, sonhador e acolhedor. As pessoas sentem em você uma aura mística. A vida o convida a fluir, sem se perder.',
    myth: 'Afrodite e Eros, que se transformaram em peixes unidos por um cordão para escapar de Tifão.',
  },
]
